#! /bin/bash

function smart_exit() {
    if [[ $1 -ne 0 ]]; then
    shift
    echo $*
    fi   
}

# exit when any command fails
set -e
# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
# trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT
trap 'smart_exit $? "\"${last_command}\" command filed with exit code $?."' EXIT
# nice_echo include
# . /home/alexandr/Documents/scripts/nice_echo
. $(realpath $(dirname $0)/../../nice_echo)

lm_echo "lab3 task1"
# LAB_PATH=/home/alexandr/GitRepos/os_lab_2019/lab3/src
LAB_PATH=$(realpath $(dirname $0)/../src)

cd $LAB_PATH
lb_echo "---PWD: $(pwd)"
lg_echo "---Build sequential_min_max"
gcc ./find_min_max.c ./sequential_min_max.c ./utils.c -o sequential_min_max
lg_echo "---Run sequential_min_max 2 5"
./sequential_min_max 1 5
lm_echo "Done"