#! /bin/bash

function smart_exit() {
    if [[ $1 -ne 0 ]]; then
    shift
    echo $*
    fi   
}

# exit when any command fails
set -e
# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
# trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT
trap 'smart_exit $? "\"${last_command}\" command filed with exit code $?."' EXIT
# nice_echo include
. /home/alexandr/Documents/scripts/nice_echo


lm_echo "task4"

LAB_PATH=/home/alexandr/GitRepos/os_lab_2019/lab2/src
SHARED_LIB_PATH=$LAB_PATH/revert_string/bin/shared

cd $LAB_PATH/tests
lb_echo "---PWD: $(pwd)"
lg_echo "---Use the shared library with LD_LIBRARY_PATH"
lg_echo "---Compile test"
gcc -c  -I../revert_string/ tests.c -o bin/tests.o
gcc bin/tests.o -lcunit  -L$SHARED_LIB_PATH -lrevstr -o tests 
lb_echo "---Run UNIT tests"
LD_LIBRARY_PATH=$SHARED_LIB_PATH $LAB_PATH/tests/tests
lm_echo "Done"